# https://aka.ms/yaml

# Setting a custom name of the build.
name: "$(date:yyyyMMdd)$(rev:.r)-$(Build.SourceBranchName)"

pool:
    vmImage: "ubuntu-latest"

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'