# https://aka.ms/yaml
# The docker-registry-endpoint "Docker Hub" is registered as a service-connection.

# Setting a custom name of the build.
name: "$(date:yyyyMMdd)$(rev:.r)"

trigger:
  - master
  - Development

variables:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    tagSuffix: ""
  ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    tagSuffix: "-prerelease"
  imagePrefix: "IMAGE_PREFIX=hanskindberg/"
  imageSuffix: "IMAGE_SUFFIX=:latest$(tagSuffix)"

jobs:
  - job: "Linux"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DockerCompose@0
        displayName: "Build"
        inputs:
          action: "Build services"
          additionalDockerComposeFiles: "Docker-Compose.Release.yml"
          additionalImageTags: "$(Build.BuildNumber)$(tagSuffix)"
          dockerComposeFile: "Docker-Compose.yml"
          dockerComposeFileArgs: |
            $(imagePrefix)
            $(imageSuffix)
          includeSourceTags: true
          qualifyImageNames: false
      - task: DockerCompose@0
        displayName: "Push"
        inputs:
          action: "Push services"
          additionalDockerComposeFiles: "Docker-Compose.Release.yml"
          additionalImageTags: "$(Build.BuildNumber)$(tagSuffix)"
          containerregistrytype: "Container Registry"
          dockerComposeFile: "Docker-Compose.yml"
          dockerComposeFileArgs: |
            $(imagePrefix)
            $(imageSuffix)
          dockerRegistryEndpoint: "Docker Hub"
          includeSourceTags: true
          qualifyImageNames: false