# https://aka.ms/yaml

# Setting a custom name of the build.
name: "$(date:yyyyMMdd)$(rev:.r)-$(Build.SourceBranchName)"

jobs:
  - job: "Windows"
    pool:
      vmImage: "vs2017-win2016"
      steps:
        - powershell: 'Write-Host "Hello!";'
          displayName: "Script 1"