# https://aka.ms/yaml

# Setting a custom name of the build.
name: "$(date:yyyyMMdd)$(rev:.r)-$(Build.SourceBranchName)"

variables:
  ${{ if ne(variables["Build.SourceBranch"], "refs/heads/masterXX") }}:
    _nonMasterBranchTagSuffix: "-$(Build.SourceBranchName)"
  imagePrefix: "IMAGE_PREFIX=hanskindberg/"
  imageSuffix: "IMAGE_SUFFIX=:latest$(_nonMasterBranchTagSuffix)"

jobs:
  - job: "Linux"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DockerCompose@0
        displayName: "Build"
        inputs:
          action: "Build services"
          additionalDockerComposeFiles: "Docker-Compose.Release.yml"
          additionalImageTags: $(name)
          containerregistrytype: "Container Registry"
          dockerComposeFile: "Docker-Compose.yml"
          dockerComposeFileArgs: |
            $(imagePrefix)
            $(imageSuffix)
          includeSourceTags: true
          qualifyImageNames: false