# https://aka.ms/yaml

# Setting a custom name of the build.
name: "$(date:yyyyMMdd)$(rev:.r)-$(Build.SourceBranchName)"

jobs:
  - job: Linux
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - script: echo Hello world!
        displayName: "Say hello"