# https://aka.ms/yaml

# Setting a custom name of the build.
name: "$(date:yyyyMMdd)$(rev:.r)-$(Build.SourceBranchName)"

variables:
  ${{ if ne( variables["Build.SourceBranch"], 'refs/heads/masterXX' ) }}:
    _suffix: "-$(Build.SourceBranchName)"
  imagePrefix: "IMAGE_PREFIX=hanskindberg/"
  imageSuffix: "IMAGE_SUFFIX=:latest$(_suffix)"

jobs:
  - job: "Linux"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - powershell: "Write-Host 'Hello: $(Build.BuildNumber)';"
        displayName: "Script"
      - task: DockerCompose@0
        displayName: "Build"
        inputs:
          action: "Build services"
          additionalDockerComposeFiles: "Docker-Compose.Release.yml"
          additionalImageTags: "$(Build.BuildNumber)"
          containerregistrytype: "Container Registry"
          dockerComposeFile: "Docker-Compose.yml"
          dockerComposeFileArgs: |
            $(imagePrefix)
            $(imageSuffix)
          includeSourceTags: true
          qualifyImageNames: false