# https://aka.ms/yaml

# Setting a custom name of the build.
name: "$(date:yyyyMMdd)$(rev:.r)-$(Build.SourceBranchName)"

variables:
  imagePrefix: "IMAGE_PREFIX=hanskindberg/"
  imageSuffix: "IMAGE_SUFFIX=:latest"
  ${{ if ne( variables['Build.SourceBranch'], 'refs/heads/masterXX' ) }}: 
    imageSuffix: "$(imageSuffix)-$(Build.SourceBranchName)"

jobs:
  - job: "Linux"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: DockerCompose@0
        displayName: "Build"
        inputs:
          action: "Build services"
          additionalDockerComposeFiles: "Docker-Compose.Release.yml"
          additionalImageTags: $(name)
          containerregistrytype: "Container Registry"
          dockerComposeFile: "Docker-Compose.yml"
          dockerComposeFileArgs: |
            $(imagePrefix)
            $(imageSuffix)
          includeSourceTags: true
          qualifyImageNames: false